basePath: /
definitions:
  hackaton-service-api_internal_entity.Video:
    properties:
      created_at:
        type: string
      error_message:
        type: string
      file_name:
        type: string
      id:
        type: string
      input_bucket:
        type: string
      input_key:
        type: string
      output_bucket:
        type: string
      output_key:
        type: string
      status:
        $ref: '#/definitions/hackaton-service-api_internal_entity.VideoStatus'
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  hackaton-service-api_internal_entity.VideoStatus:
    enum:
    - PENDING
    - PROCESSING
    - DONE
    - ERROR
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusProcessing
    - StatusDone
    - StatusError
  internal_handler.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  internal_handler.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para upload e gerenciamento de processamento de vídeos.
  title: FIAP X - API de Processamento de Vídeos
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e retorna um token JWT
      parameters:
      - description: Credenciais de Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Realiza login do usuário
      tags:
      - Auth
  /api/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registra um novo usuário
      tags:
      - Auth
  /api/upload:
    post:
      consumes:
      - multipart/form-data
      description: Faz o upload de um arquivo de vídeo para processamento
      parameters:
      - description: Arquivo de vídeo (.mp4, .mkv, .avi)
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Realiza o upload de um vídeo
      tags:
      - Videos
  /api/videos:
    get:
      description: Retorna todos os vídeos enviados pelo usuário logado
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/hackaton-service-api_internal_entity.Video'
            type: array
      security:
      - BearerAuth: []
      summary: Lista vídeos do usuário
      tags:
      - Videos
  /api/videos/{id}/download:
    get:
      description: Retorna uma URL assinada do S3 para baixar o arquivo ZIP com os
        frames. O vídeo deve estar com status 'DONE'.
      parameters:
      - description: ID do Vídeo
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'link: http://s3.url...'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Acesso negado
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Vídeo não encontrado
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Vídeo não está pronto
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Gera link para download do vídeo processado
      tags:
      - Videos
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
